version: "3"
services:
  server:
    image: node:22.2.0-slim
    command: node dist/src/server.js
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    environment:
      - BROWSERLESS_ENDPOINT=ws://browserless:3000?token=6R0W53R135510
    ports:
      - "80:80"
    networks:
      - scheduler-network

  scheduler:
    image: node:22.2.0-slim
    command: node dist/src/index.js
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    environment:
      - BROWSERLESS_ENDPOINT=ws://browserless:3000?token=6R0W53R135510
      - REDIS_HOST=redis
    networks:
      - scheduler-network

  browserless:
    hostname: browserless
    image: browserless/chrome:latest
    ports:
      - "8080:3000"
    environment:
      DEFAULT_HEADLESS: true
      TOKEN: 6R0W53R135510
    networks:
      - scheduler-network

  redis:
    image: "redis:alpine3.19"
    ports:
      - "6379:6379"
    networks:
      - scheduler-network

networks:
  scheduler-network:
