version: "3"
services:
  browserless:
    hostname: browserless
    image: browserless/chrome:latest
    ports:
      - 8080:3000
    environment:
      DEFAULT_HEADLESS: true
      TOKEN: 6R0W53R135510
    networks:
      - scheduler-network

  redis:
    image: "redis:alpine3.19"
    ports:
      - 6379:6379
    networks:
      - scheduler-network

networks:
  scheduler-network: